# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
substitutions:
  _TERRAFORM_VERSION: 0.12.20
  _TERRAFORM_VERSION_SHA256SUM: 46bd906f8cb9bbb871905ecb23ae7344af8017d214d735fbb6d6c8e0feb20ff3

steps:
  - name: 'gcr.io/cloud-builders/wget'
    args: ["https://releases.hashicorp.com/terraform/${_TERRAFORM_VERSION}/terraform_${_TERRAFORM_VERSION}_linux_amd64.zip"]

  - name: gcr.io/kaniko-project/executor
    env:
      - 'TERRAFORM_VERSION=${_TERRAFORM_VERSION}'
      - 'TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}'
    args:
    - --destination=gcr.io/$PROJECT_ID/image
    - --cache=true
    - --cache-ttl=24h
    - --build-arg
    - TERRAFORM_VERSION=${_TERRAFORM_VERSION}
    - --build-arg
    - TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}

images:
  - gcr.io/${PROJECT_ID}/builder-terraform:${_TERRAFORM_VERSION}
