options:
  env:
    -
substitutions:
  _ORG: Cyclingwithelephants

steps:
  - name: terraform:0.12
    id: first
    sh: echo hello
  - name: hugo
    timeout: 30s
    sh: |
        function get_env() {
          # BRANCH_NAME is a cloudbuild built-in variable

          if [[ ${BRANCH_NAME} ]]; then
            if [[ ${BRANCH_NAME} == "master" ]]; then
              env='prod'
            else
              # _PR_NUMBER is a github cloudbuild built-in
              env="dev-${BRANCH_NAME}"
            fi
          else # is being executed locally
            branch_name=$(git symbolic-ref --short HEAD)
            if [[ ${branch_name} == "master" ]]; then
              env='prod'
            else
              env="dev-${branch_name}"
            fi
          fi
          echo ${env}
        }
